# Generated by Django 3.0.8 on 2020-07-23 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIT', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('adress', models.CharField(max_length=100)),
                ('NRC', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'MASCULINO'), ('female', 'FEMENINO')], default='contado', max_length=10)),
                ('state', models.CharField(choices=[('active', 'ACTIVO'), ('inactive', 'INACTIVO')], default='contado', max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Contacto')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo')),
                ('phone', models.IntegerField(null=True, verbose_name='Telefono')),
                ('cellPhone', models.IntegerField(verbose_name='Celular')),
                ('degree', models.CharField(choices=[('primary', 'PRINCIPAL'), ('secondary', 'SEGUNDARIO'), ('tertiary', 'TERCIARIO')], default='primary', max_length=10, verbose_name='Nivel Contacto')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Empresa Proveedora')),
                ('adress', models.CharField(max_length=100, verbose_name='Direccion')),
                ('NIT', models.CharField(max_length=50)),
                ('phone', models.IntegerField(verbose_name='Telefono Empresa')),
                ('FAX', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('active', 'ACTIVO'), ('inactive', 'INACTIVO')], default='active', max_length=10, verbose_name='Estado')),
                ('date', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.Contact')),
            ],
        ),
    ]
