# Generated by Django 3.0.8 on 2020-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
