# Generated by Django 3.0.8 on 2020-07-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200719_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
