# Generated by Django 3.0.8 on 2020-07-30 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='activado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
