# Generated by Django 3.0.8 on 2020-07-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Limpieza', 'Limpieza'), ('Papelerìa', 'Papelerìa'), ('Verduras', 'Verduras')], max_length=10),
        ),
    ]
