# Generated by Django 3.0.8 on 2020-07-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='pago',
            field=models.CharField(choices=[('contado', 'CONTADO'), ('partes', 'PARTES')], default='contado', max_length=10),
        ),
    ]
