# Generated by Django 3.0.8 on 2020-07-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200711_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pago',
            field=models.CharField(choices=[('contado', 'CONTADO'), ('credito', 'CREDITO')], default='contado', max_length=10),
        ),
    ]
